name: Build and deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  RUST_TARGET: x86_64-unknown-linux-gnu
  REPOS_PATH: /home/runner/work/fvd_replay_parser_cli/fvd_replay_parser_cli

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'fvd_replay_parser_cli'

      - uses: actions/checkout@v4
        with:
          repository: 'tmk907/aoe2rec'
          path: 'aoe2rec'
          ref: fvd-parser

      # - name: Replace text using sed
      #   run: |
      #     sed -i 's#\"../../../aoe2rec/crates/aoe2rec\"#\"/home/runner/work/aoe2rec/crates/aoe2rec\"#g' ${{ env.REPOS_PATH }}/fvd_replay_parser_cli/Cargo.toml

      - name: Show source tree
        run: tree -L 3
        working-directory: ./fvd_replay_parser_cli

      - name: Build release binary
        run: cargo build --release 
        working-directory: ./fvd_replay_parser_cli

      - name: Show source tree
        run: tree -L 3
        working-directory: ./fvd_replay_parser_cli
      #        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rust-musl-binary
          path: ./fvd_replay_parser_cli/target/release/fvd_replay_parser_cli

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >>~/.ssh/config <<END
          Host vps
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/id_ed25519
              StrictHostKeyChecking no
              IdentitiesOnly yes
              PasswordAuthentication no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_KEY: ${{ secrets.SERVER_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}
      
      # Transfer Dockerfile
      # - name: Copy Dockerfile
      #   run: |
      #     ssh vps "mkdir -p /srv/www/fvd"
      #     scp "$projectDir/Dockerfile" vps:"/srv/www/fvd"

      # Copy confg file
      - name: Copy config file
        run: |
          ssh vps << EOF
            cp ./fvd_replay_parser_cli/target/release/fvd_replay_parser_cli /srv/www/fvd/fvd_replay_parser_cli
          EOF

      # Remove shh files
      - name: Remove ssh files
        run: |
          rm ~/.ssh/id_ed25519
          rm ~/.ssh/config
          