name: Build and deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  RUST_TARGET: x86_64-unknown-linux-musl
  REPOS_PATH: /home/runner/work/fvd_replay_parser_cli/fvd_replay_parser_cli

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'fvd_replay_parser_cli'

      - uses: actions/checkout@v4
        with:
          repository: 'tmk907/aoe2rec'
          path: 'aoe2rec'
          ref: fvd-parser

      # - name: Install Rust
      #   uses: actions-rust-lang/setup-rust-toolchain@v1
      #   with:
      #     toolchain: stable
      #     target: ${{ env.RUST_TARGET }}
      #     override: true

      - name: Add musl target
        run: rustup target add ${{ env.RUST_TARGET }}

      - name: Build release binary
        run: cargo build --release --target ${{ env.RUST_TARGET }}
        working-directory: ./fvd_replay_parser_cli

      - name: Show source tree
        run: tree -L 3
        working-directory: ./fvd_replay_parser_cli
      #        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fvd_replay_parser_cli
          path: ./fvd_replay_parser_cli/target/${{ env.RUST_TARGET }}/release/fvd_replay_parser_cli

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >>~/.ssh/config <<END
          Host vps
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/id_ed25519
              StrictHostKeyChecking no
              IdentitiesOnly yes
              PasswordAuthentication no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_KEY: ${{ secrets.SERVER_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}

      # Copy confg file
      - name: Copy config file
        run: |
          ssh vps << EOF
            cp ${{ env.REPOS_PATH }}/fvd_replay_parser_cli/target/${{ env.RUST_TARGET }}/release/fvd_replay_parser_cli /srv/www/fvd/fvd_replay_parser_cli
          EOF

      # Remove shh files
      - name: Remove ssh files
        run: |
          rm ~/.ssh/id_ed25519
          rm ~/.ssh/config
          